"use client";
import { useMemo, useState } from "react";
import type { DemoState, Patient, Prescription, Role } from "../../lib/types";
import { AppShell } from "./app-shell"; import { type ViewId } from "./constants"; import { OverviewView } from "./overview-view"; import { PatientDrawer } from "./patient-drawer"; import { PatientsView } from "./patients-view"; import { DoctorRosterView, ReferenceSectionView } from "./support-views"; import { ConsultationDialog, TriageDialog } from "./workflow-dialogs"; import { AuditView, BillingView, PharmacyView, QueueView, TriageView } from "./workspace-views";

export function CareFlowApp({ role, displayName, initialData }: { role: Role; displayName: string; initialData: DemoState }) {
  const [data, setData] = useState(initialData), [view, setView] = useState<ViewId>("overview"), [query, setQuery] = useState(""), [selectedId, setSelectedId] = useState<string | null>(null), [notice, setNotice] = useState(""), [busy, setBusy] = useState(false), [mobileNav, setMobileNav] = useState(false), [triageOpen, setTriageOpen] = useState(false), [consultOpen, setConsultOpen] = useState(false);
  const patients = useMemo(() => data.patients.filter((p) => `${p.name} ${p.queueNumber} ${p.department}`.toLowerCase().includes(query.toLowerCase())), [data.patients, query]); const queue = useMemo(() => data.patients.filter((p) => ["waiting", "triage"].includes(p.stage)).sort((a, b) => ({ critical: 0, urgent: 1, soon: 2, routine: 3 })[a.priority] - ({ critical: 0, urgent: 1, soon: 2, routine: 3 })[b.priority] || a.arrival.localeCompare(b.arrival)), [data.patients]); const active = selectedId ? data.patients.find((p) => p.id === selectedId) ?? null : null; const can = (roles: Role[]) => roles.includes(role) || role === "Admin"; const total = (p: Patient) => p.billing.consultation + p.billing.labs + p.billing.medication;
  const refresh = async () => { const response = await fetch("/api/workspace", { cache: "no-store" }); if (!response.ok) throw new Error("Could not refresh the workspace"); setData((await response.json()).data as DemoState); };
  const mutate = async (path: string, body: unknown, message: string) => { setBusy(true); try { const response = await fetch(path, { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify(body) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message ?? "The action could not be completed"); await refresh(); setSelectedId(null); setTriageOpen(false); setConsultOpen(false); setNotice(message); window.setTimeout(() => setNotice(""), 4000); } catch (error) { setNotice((error as Error).message); } finally { setBusy(false); } };
  const open = (p: Patient) => setSelectedId(p.id), openTriage = (p: Patient) => { setSelectedId(p.id); setTriageOpen(true); }; const dispense = (p: Patient, rx: Prescription) => { if (p.visitId && p.visitVersion && rx.id) void mutate(`/api/visits/${p.visitId}/dispense`, { version: p.visitVersion, prescriptionId: rx.id }, "Prescription dispensed"); }; const pay = (p: Patient) => { if (p.visitId && p.visitVersion && p.invoiceVersion) void mutate(`/api/visits/${p.visitId}/payment`, { visitVersion: p.visitVersion, invoiceVersion: p.invoiceVersion, method: "CASH" }, `${p.name} paid and discharged`); };
  const content = view === "overview" ? <OverviewView data={data} queue={queue} onView={setView} onSelect={open} /> : view === "patients" ? <PatientsView patients={patients} query={query} onSelect={open} /> : view === "queue" ? <QueueView patients={queue} onSelect={open} onTriage={openTriage} can={can} /> : view === "triage" ? <TriageView patients={data.patients} onSelect={openTriage} /> : view === "consultation" ? <DoctorRosterView data={data} /> : view === "pharmacy" ? <PharmacyView data={data} onSelect={open} can={can} onDispense={dispense} busy={busy} /> : view === "billing" ? <BillingView data={data} onSelect={open} can={can} onPay={pay} busy={busy} total={total} /> : view === "audit" ? <AuditView data={data} /> : <ReferenceSectionView view={view as "appointments" | "services" | "analytics" | "users" | "departments" | "settings"} />;
  return <AppShell view={view} setView={setView} role={role} displayName={displayName} query={query} setQuery={setQuery} mobileNav={mobileNav} setMobileNav={setMobileNav} queueCount={queue.length} patients={data.patients} notice={notice}>{content}{active && !triageOpen && !consultOpen && <PatientDrawer patient={active} onClose={() => setSelectedId(null)} onTriage={() => setTriageOpen(true)} onConsult={() => setConsultOpen(true)} onView={setView} can={can} />}{active && triageOpen && <TriageDialog patient={active} onClose={() => setTriageOpen(false)} onSave={(form) => { if (active.visitId && active.visitVersion) void mutate(`/api/visits/${active.visitId}/triage`, { version: active.visitVersion, temperature: Number(form.temperature), bloodPressure: form.bloodPressure, heartRate: Number(form.heartRate), oxygenSat: Number(form.spo2), symptoms: form.symptoms, notes: form.notes, priority: form.priority.toUpperCase() }, `${active.name} advanced to consultation`); }} />}{active && consultOpen && <ConsultationDialog patient={active} data={data} onClose={() => setConsultOpen(false)} onSave={(form) => { if (active.visitId && active.visitVersion) void mutate(`/api/visits/${active.visitId}/consultation`, { ...form, version: active.visitVersion }, `${active.name} consultation completed`); }} />}</AppShell>;
}
