"use client";

import { useEffect, useRef, useState } from "react";
import { X } from "lucide-react";
import type { DemoState, Patient, Priority } from "../../lib/types";
import { priorityLabel } from "./constants";

export function Field({ label, value, onChange, placeholder, textarea, type = "text", required }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; textarea?: boolean; type?: string; required?: boolean }) { return <label className="field"><span>{label}{required && <em>required</em>}</span>{textarea ? <textarea value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} rows={3} required={required} /> : <input type={type} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} required={required} />}</label>; }
export function Modal({ title, subtitle, onClose, children, kicker = "Clinical workflow" }: { title: string; subtitle: string; onClose: () => void; children: React.ReactNode; kicker?: string }) {
  const closeRef = useRef<HTMLButtonElement>(null);
  useEffect(() => {
    const previous = document.activeElement as HTMLElement | null;
    const closeOnEscape = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); };
    closeRef.current?.focus();
    window.addEventListener("keydown", closeOnEscape);
    return () => { window.removeEventListener("keydown", closeOnEscape); previous?.focus(); };
  }, [onClose]);
  return <div className="modal-overlay"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="workflow-title"><div className="modal-head"><div><span className="record-kicker">{kicker}</span><h2 id="workflow-title">{title}</h2><p className="muted">{subtitle}</p></div><button ref={closeRef} className="icon-button" onClick={onClose} aria-label="Close dialog"><X size={18} /></button></div>{children}</section></div>;
}
export function TriageDialog({ patient, onClose, onSave }: { patient: Patient; onClose: () => void; onSave: (data: { temperature: string; bloodPressure: string; heartRate: string; spo2: string; symptoms: string; notes: string; priority: Priority }) => void }) { const [form, setForm] = useState({ temperature: "", bloodPressure: "", heartRate: "", spo2: "", symptoms: patient.symptoms, notes: "", priority: patient.priority }); const set = (key: keyof typeof form, value: string) => setForm((old) => ({ ...old, [key]: value })); const ready = [form.temperature, form.bloodPressure, form.heartRate, form.spo2].every(Boolean); return <Modal title="Record triage" subtitle={`${patient.queueNumber} · ${patient.name}`} onClose={onClose}><div className="form-grid"><Field label="Temperature (°C)" value={form.temperature} onChange={(v) => set("temperature", v)} placeholder="36.8" required /><Field label="Blood pressure" value={form.bloodPressure} onChange={(v) => set("bloodPressure", v)} placeholder="120/80" required /><Field label="Heart rate (bpm)" value={form.heartRate} onChange={(v) => set("heartRate", v)} placeholder="72" required /><Field label="SpO2 (%)" value={form.spo2} onChange={(v) => set("spo2", v)} placeholder="98" required /></div><Field label="Symptoms" value={form.symptoms} onChange={(v) => set("symptoms", v)} /><Field label="Nursing notes" value={form.notes} onChange={(v) => set("notes", v)} textarea placeholder="Observed presentation, patient notes…" /><label className="field"><span>Priority<em>required</em></span><select value={form.priority} onChange={(event) => set("priority", event.target.value)}>{Object.keys(priorityLabel).map((priority) => <option key={priority} value={priority}>{priorityLabel[priority as Priority]}</option>)}</select></label><div className="modal-actions"><button className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={!ready} onClick={() => onSave(form)}>Save triage</button></div></Modal>; }
export function ConsultationDialog({ patient, data, onClose, onSave }: { patient: Patient; data: DemoState; onClose: () => void; onSave: (data: { findings: string; diagnosis: string; prescriptions: { medicationId: string; quantity: number; directions: string }[]; labServiceIds: string[]; followUp: string | null }) => void }) { const [findings, setFindings] = useState(""); const [diagnosis, setDiagnosis] = useState(""); const [medicineId, setMedicineId] = useState(data.inventory[0]?.id ?? ""); const [quantity, setQuantity] = useState("10"); const [directions, setDirections] = useState("As directed"); const [labs, setLabs] = useState<string[]>([]); const [followUp, setFollowUp] = useState(""); const ready = findings.trim().length > 0 && diagnosis.trim().length > 0; return <Modal title="Complete consultation" subtitle={`${patient.queueNumber} · ${patient.name}`} onClose={onClose}><Field label="Findings" value={findings} onChange={setFindings} textarea required /><Field label="Diagnosis" value={diagnosis} onChange={setDiagnosis} textarea required /><div className="form-grid"><label className="field"><span>Medicine</span><select value={medicineId} onChange={(event) => setMedicineId(event.target.value)}><option value="">No medication</option>{data.inventory.map((medicine) => <option key={medicine.id} value={medicine.id}>{medicine.name} · {medicine.stock} available</option>)}</select></label><Field label="Quantity" value={quantity} onChange={setQuantity} type="number" /><Field label="Directions" value={directions} onChange={setDirections} /></div><label className="field"><span>Request labs</span><div className="check-options">{data.labServices.map((lab) => <label key={lab.id}><input type="checkbox" checked={labs.includes(lab.id)} onChange={(event) => setLabs(event.target.checked ? [...labs, lab.id] : labs.filter((item) => item !== lab.id))} />{lab.name}</label>)}</div></label><Field label="Follow-up" value={followUp} onChange={setFollowUp} /><div className="modal-actions"><button className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={!ready} onClick={() => onSave({ findings, diagnosis, prescriptions: medicineId ? [{ medicationId: medicineId, quantity: Number(quantity), directions }] : [], labServiceIds: labs, followUp: followUp || null })}>Complete consultation</button></div></Modal>; }
