-- Human-readable identifiers are generated by PostgreSQL sequences so concurrent registrations remain unique.
CREATE SEQUENCE careflow_mrn_seq START WITH 1009;
CREATE SEQUENCE careflow_queue_token_seq START WITH 21;
